apiVersion: apps/v1
kind: Deployment
metadata:
  name: nton-web-app
  labels:
    app: hello-world-nton
spec:
  replicas: 1 # Scale parameter: tells K8s to always keep exactly 1 copy alive
  selector:
    matchLabels:
      app: hello-world-nton
  template:
    metadata:
      labels:
        app: hello-world-nton
    spec:
      containers:
      - name: web-container
        image: nton-app:v1 # Pulls the exact custom image we built in Phase 2!
        imagePullPolicy: Never # Crucial: tells K8s to look inside Minikube's local registry rather than Docker Hub
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nton-web-service
spec:
  type: NodePort # Exposes the pod network so your laptop can talk to the container
  selector:
    app: hello-world-nton
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32000 # Fixes the entry port to exactly 32000 on your cluster IP
